### ISSUE TITLE
init_app usability

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo_template_app#1] opened 2016-09-08 17:33 UTC
```
$ ./manage.sh init_app
Enter the plugin name : demo
...
About to write to /vagrant/plugins/demo/package.json:
...
Is this ok? (yes) n
Aborted.
ready
```
but it got written anyway? I'm not sure a confirmation is necessary, particularly if we'll create the project in any event.
```
$ ls /vagrant/plugins/demo
_deploy  index.html  LICENSE  main.js  package.json  README.md  style.scss
```
Then if I try to use the same name, I get a "fatal" error, and then execution continues? If we want to be extra safe and abort that's ok, or we could trust the user and clobber, but the current behavior seems inconsistent?
```
vagrant@caleydo-web:/vagrant$ ./manage.sh init_app
Enter the plugin name : demo
fatal: destination path 'demo' already exists and is not an empty directory.
error: Could not remove config section 'remote.origin'
...
name: (sample_app) xxx
version: (0.0.1) 
entry point: (main.js) 
test command: 
keywords: 
author: 
license: (SEE LICENSE IN LICENSE) 
About to write to /vagrant/plugins/demo/package.json:

{
  "name": "xxx",
  "description": "A simple sample application as a starting point for your own one",
  "version": "0.0.1",
  "license": "SEE LICENSE IN LICENSE",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/caleydo/sample_app.git"
  },
...
    "plugins": {
      "web": {
        "type": "app",
        "name": "Sample"
      }
...
    "products": [
      {
        "name": "Sample",
...
        "app": "sample_app",
        "plugins": [
          "sample_app"
        ]
      }
    ]
  },...
  "bugs": {
    "url": "https://github.com/caleydo/sample_app/issues"
  },...
}
```
Should the user supplied name be injected in all the places we have "sample_app" here? Do you want to check for name collisions on github? Would it be good to just prompt for name once? I'm not sure why "Enter the plugin name" and "name" should be different.

**Comment by mstreit** [comment] 2016-09-09 12:32
Yes, asking twice for the same is not ideal. The problem is that the script asks for the name and then `npm init` asks for it again. I suggest to completely remove `npm init` and tell the user in the documentation that he is supposed to update the information in the package.json in an editor.

**Comment by mstreit** [comment] 2016-09-09 13:16
@mccalluc It seems that your caleydo_web_container repo was outdated because I already removed the `nmp init` call yesterday before you've tested it. Can you please check again?

**Comment by mccalluc** [comment] 2016-09-09 14:10
Sorry about that.
- Just made sure I was on master caleydo_web_container and pulled the latest changes, with no local changes.
- `vagrant destory`ed other VMs to avoid confusion.
- Followed the steps on http://www.caleydo.org/documentation/vagrant/ and that worked.
- `./manage.sh init_app` only prompted me for the name once. yay.
- `./manage.sh resolve` seemed to work.
- `./manage.sh server`:
```
+ grunt server
Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "ts:dev" (ts) task
Updated reference file (7ms).
Compiling...
Cleared fast compile cache for target: dev
...
Using tsc v1.8.10
plugins/caleydo_clue/template.ts(455,29): error TS2339: Property 'optionsDialog' does not exist on type 'AppHeader'.

>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:dev" failed. Use --force to continue.

Aborted due to warnings.
```
and the server did not come up.

**Comment by mstreit** [comment] 2016-09-12 08:09
@thinkh Is this issue caused by your recent CLUE dependency changes?

**Comment by mstreit** [comment] 2016-09-13 08:47
Fixed in https://github.com/Caleydo/caleydo_core/commit/ddd4064ee00762c2fa021092a24a4d34125f1a03. The template app has no dependency to caleydo_clue anymore.

**Closed by mstreit** 2016-09-13 08:47 UTC
